// Mocks generated by Mockito 5.0.16 from annotations
// in mobile/test/settings_screen_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:mobile/api/rest_client.dart' as _i5;
import 'package:mobile/app_settings.dart' as _i2;
import 'package:mobile/version.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:package_info/package_info.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAppSettings_0 extends _i1.Fake implements _i2.AppSettings {}

class _FakePackageInfo_1 extends _i1.Fake implements _i3.PackageInfo {}

/// A class which mocks [Version].
///
/// See the documentation for Mockito's code generation for more information.
class MockVersion extends _i1.Mock implements _i4.Version {
  MockVersion() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppSettings get settings =>
      (super.noSuchMethod(Invocation.getter(#settings),
          returnValue: _FakeAppSettings_0()) as _i2.AppSettings);
  @override
  _i3.PackageInfo get info => (super.noSuchMethod(Invocation.getter(#info),
      returnValue: _FakePackageInfo_1()) as _i3.PackageInfo);
  @override
  String get version =>
      (super.noSuchMethod(Invocation.getter(#version), returnValue: '')
          as String);
  @override
  int get versionCode =>
      (super.noSuchMethod(Invocation.getter(#versionCode), returnValue: 0)
          as int);
  @override
  int get lastKnownVersionCode =>
      (super.noSuchMethod(Invocation.getter(#lastKnownVersionCode),
          returnValue: 0) as int);
  @override
  bool get isInitialVersion =>
      (super.noSuchMethod(Invocation.getter(#isInitialVersion),
          returnValue: false) as bool);
  @override
  _i4.VersionState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i4.VersionState.INITIAL) as _i4.VersionState);
  @override
  void updateVersionState() =>
      super.noSuchMethod(Invocation.method(#updateVersionState, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestClient extends _i1.Mock implements _i5.RestClient {
  MockRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get authority =>
      (super.noSuchMethod(Invocation.getter(#authority), returnValue: '')
          as String);
  @override
  String get encoding =>
      (super.noSuchMethod(Invocation.getter(#encoding), returnValue: '')
          as String);
  @override
  List<String> get dummyMessages =>
      (super.noSuchMethod(Invocation.getter(#dummyMessages),
          returnValue: <String>[]) as List<String>);
  @override
  _i6.Future<String> getRegions(String? regionName) =>
      (super.noSuchMethod(Invocation.method(#getRegions, [regionName]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> getRegionsByType(
          String? regionName, List<String>? regionLevels) =>
      (super.noSuchMethod(
          Invocation.method(#getRegionsByType, [regionName, regionLevels]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> getRegionHierarchyById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getRegionHierarchyById, [id]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> getRegionHierarchyByCoordinates(
          double? lat, double? long) =>
      (super.noSuchMethod(
          Invocation.method(#getRegionHierarchyByCoordinates, [lat, long]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> fetchMessages(String? ars, int? size, int? page) =>
      (super.noSuchMethod(Invocation.method(#fetchMessages, [ars, size, page]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  String toString() => super.toString();
}
