name: mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.w
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+47

environment:
  sdk: ">=2.12.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  streaming_shared_preferences: ^2.0.0
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.0
  cupertino_list_tile: ^0.2.0-nullsafety.0
  easy_localization: ^3.0.0
  fimber: ^0.6.1
  flutter_animator: ^3.1.1
  flutter_platform_widgets: ^1.0.1-nullsafety.2
  flutter_typeahead: ^3.2.0
  get_it: ^7.2.0
  http: ^0.13.0
  infinite_scroll_pagination: ^3.0.1
  location: ^4.1.1
  modal_bottom_sheet: ^2.0.0
  optional: ^6.0.0-nullsafety.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.5
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build: ^2.0.0
  build_runner: ^2.0.6
  convert: ^3.0.0
  crypto: ^3.0.0
  intl: ^0.17.0
  json_serializable: ^6.0.1
  mockito: ^5.0.2

publish_to: none

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/dealog_iconlogo_iOS.png"
  image_path_android: "assets/images/dealog_iconlogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
